name = "rcerrud/justvalidators"
version = "0.0.1"
license = "Apache-2.0"
description = "Aiken contracts for project 'rcerrud/justvalidators'"

[repository]
user = "rcerrud"
project = "justvalidators"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
